# Generated by Django 5.0.1 on 2024-02-15 03:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'T_AdministrationGeneral',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'T_Formation',
            },
        ),
        migrations.CreateModel(
            name='ProgrammeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=255)),
                ('dateDeb', models.DateField()),
                ('dateFin', models.DateField()),
            ],
            options={
                'db_table': 'T_ProgrammeFormation',
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'T_Statut',
            },
        ),
        migrations.CreateModel(
            name='TypeBanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'T_TypeBanque',
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typedocument', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'T_Typedocument',
            },
        ),
        migrations.CreateModel(
            name='TypeLettre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'T_TypeLettre',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcategorie', models.CharField(max_length=100)),
                ('administrationGeneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.administrationgeneral')),
            ],
            options={
                'db_table': 'T_Categorie',
            },
        ),
        migrations.CreateModel(
            name='HFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=50)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.formation')),
            ],
            options={
                'db_table': 'T_HFormation',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('hierarchie', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=50)),
                ('fonction', models.CharField(max_length=80)),
                ('specialite', models.CharField(max_length=81)),
                ('no_acte_affectation', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('diplome', models.CharField(max_length=50)),
                ('dateNaissance', models.DateField()),
                ('date_enregistrement', models.DateField()),
                ('date_affectation', models.DateField()),
                ('telephone', models.CharField(max_length=50)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.categorie')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.statut')),
            ],
            options={
                'db_table': 'T_Personnel',
            },
        ),
        migrations.CreateModel(
            name='LettreBanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombanque', models.CharField(max_length=50)),
                ('numerobanque', models.CharField(max_length=50)),
                ('typebanque', models.CharField(max_length=50)),
                ('datejour', models.DateField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel')),
            ],
            options={
                'db_table': 'T_LettreBanque',
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel'),
        ),
        migrations.AddField(
            model_name='formation',
            name='programmeFormation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.programmeformation'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDocument', models.CharField(max_length=30)),
                ('document', models.FileField(blank=True, null=True, upload_to='stock_document')),
                ('dateEnregistrement', models.DateField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel')),
                ('typeDocument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.typedocument')),
            ],
            options={
                'db_table': 'T_Document',
            },
        ),
        migrations.CreateModel(
            name='Lettre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejour', models.DateField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel')),
                ('typelettre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.typelettre')),
            ],
            options={
                'db_table': 'T_Lettre',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('poste', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='utilisateur_groups', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='utilisateur_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'T_Utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeconges', models.CharField(max_length=50)),
                ('dateDeb', models.DateField()),
                ('dateFin', models.DateField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel')),
            ],
            options={
                'db_table': 'T_Conge',
                'unique_together': {('personnel', 'dateDeb', 'dateFin')},
            },
        ),
    ]
