# Generated by Django 5.0.1 on 2024-04-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('administrationGeneral', 'nomcategorie')},
        ),
    ]
