# Generated by Django 4.2.7 on 2024-02-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'T_Statut',
            },
        ),
        migrations.AlterField(
            model_name='personnel',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.statut'),
        ),
    ]
