# Generated by Django 5.0.1 on 2024-04-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_alter_categorie_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personnel',
            unique_together={('matricule',)},
        ),
    ]
