# Generated by Django 4.2.7 on 2024-02-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_typebanque_typelettre_lettrebanque_lettre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenererRapport',
        ),
        migrations.DeleteModel(
            name='RapportAnalytiques',
        ),
    ]
