# Generated by Django 5.0.1 on 2024-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_hconge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=50),
        ),
    ]
