# Generated by Django 5.0.1 on 2024-04-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_personnel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formation',
            unique_together={('personnel',)},
        ),
    ]
