# Generated by Django 5.0.1 on 2024-05-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_alter_personnel_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='hierarchie',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('C', 'C'), ('CP', 'CP')], default='CP', max_length=50),
        ),
    ]
