# Generated by Django 5.0.1 on 2024-05-08 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_alter_personnel_hierarchie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettrebanque',
            name='typebanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.typebanque'),
        ),
    ]
